# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('tara', models.CharField(max_length=100)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('taste', models.CharField(max_length=100)),
            ],
        ),
    ]
