# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soda',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
