# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_soda_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='img',
            field=models.ImageField(upload_to=None),
        ),
    ]
