# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20170811_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='img',
            field=models.CharField(blank=True, help_text='Изображение', max_length=100),
        ),
    ]
