# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20170811_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='img',
            field=models.ImageField(help_text='Изображение', null=True, upload_to=''),
        ),
    ]
