# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_auto_20170811_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soda',
            name='img',
        ),
        migrations.AddField(
            model_name='soda',
            name='photo',
            field=models.ImageField(blank=True, help_text='Изображение', upload_to=''),
        ),
    ]
