# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0009_auto_20170812_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'напиток', 'verbose_name_plural': 'напитки'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='descr',
            field=models.TextField(blank=True, help_text='Информация о бренде', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением логотипа', upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Название бренда', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='tara',
            field=models.CharField(help_text='Материал бутылки', max_length=100, verbose_name='Тара'),
        ),
    ]
