# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_auto_20170812_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, help_text='Материал бутылки', max_length=100, verbose_name='Тара')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Объем бутылки, л.', max_digits=4, verbose_name='Объем')),
                ('photo', models.ImageField(blank=True, help_text='Выберите файл с изображением', upload_to='', verbose_name='Фото')),
                ('storage', models.TextField(blank=True, help_text='Срок и условия хранения', verbose_name='Хранение')),
                ('pack_quant', models.IntegerField(blank=True, help_text='Количество бутылок в упаковке, шт.', verbose_name='Кол-во бутылок')),
                ('pack_length', models.IntegerField(blank=True, help_text='Длина упаковки, мм.', verbose_name='Длина упаковки')),
                ('pack_width', models.IntegerField(blank=True, help_text='Ширина упаковки, мм.', verbose_name='Ширина упаковки')),
                ('pack_height', models.IntegerField(blank=True, help_text='Высота упаковки, мм.', verbose_name='Высота упаковки')),
                ('pack_weight', models.DecimalField(blank=True, decimal_places=1, help_text='Вес брутто упаковки, кг.', max_digits=3, verbose_name='Вес упаковки')),
                ('pallet_length', models.DecimalField(blank=True, decimal_places=1, help_text='Длина поддона, м.', max_digits=2, verbose_name='Длина поддона')),
                ('pallet_width', models.DecimalField(blank=True, decimal_places=1, help_text='Ширина поддона, м.', max_digits=2, verbose_name='Ширина поддона')),
                ('pallet_quant', models.IntegerField(blank=True, help_text='Количество бутылок на поддоне, шт.', verbose_name='Кол-во бутылок')),
                ('pallet_weight_bru', models.DecimalField(blank=True, decimal_places=1, help_text='Масса брутто поддона, кг.', max_digits=5, verbose_name='Масса брутто')),
                ('pallet_weight_net', models.DecimalField(blank=True, decimal_places=1, help_text='Масса нетто поддона, кг.', max_digits=5, verbose_name='Масса нетто')),
            ],
            options={
                'verbose_name': 'тара',
                'verbose_name_plural': 'тара',
            },
        ),
        migrations.RemoveField(
            model_name='drink',
            name='volume',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, help_text='Название бренда', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='tara',
            field=models.ForeignKey(blank=True, help_text='Выберите тару', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Tara', verbose_name='тара'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='taste',
            field=models.CharField(blank=True, help_text='Вкус.', max_length=100, verbose_name='Вкус'),
        ),
        migrations.AddField(
            model_name='tara',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='бренд'),
        ),
    ]
