# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20170907_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением логотипа', upload_to='siteapp/img', verbose_name='Логотип'),
        ),
    ]
