# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_auto_20170908_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением логотипа', upload_to='img/', verbose_name='Логотип'),
        ),
    ]
