# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_auto_20170909_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением логотипа', upload_to='img/goods', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением', upload_to='img/goods', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='photo',
            field=models.ImageField(blank=True, help_text='Выберите файл с изображением', upload_to='img/goods', verbose_name='Фото'),
        ),
    ]
