# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0016_auto_20170909_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='material',
            field=models.CharField(blank=True, help_text='Материал бутылки (ПЭТ, стекло...)', max_length=100, verbose_name='Тара'),
        ),
    ]
