# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_auto_20170909_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='pack_quant',
            field=models.IntegerField(blank=True, help_text='Количество бутылок в упаковке, шт.', null=True, verbose_name='Кол-во бутылок'),
        ),
    ]
