# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_auto_20171201_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='pack_height',
            field=models.IntegerField(blank=True, help_text='Высота упаковки, мм.', null=True, verbose_name='Высота упаковки'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_length',
            field=models.IntegerField(blank=True, help_text='Длина упаковки, мм.', null=True, verbose_name='Длина упаковки'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Вес брутто упаковки, кг.', max_digits=3, null=True, verbose_name='Вес упаковки'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_width',
            field=models.IntegerField(blank=True, help_text='Ширина упаковки, мм.', null=True, verbose_name='Ширина упаковки'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Длина поддона, м.', max_digits=2, null=True, verbose_name='Длина поддона'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_quant',
            field=models.IntegerField(blank=True, help_text='Количество бутылок на поддоне, шт.', null=True, verbose_name='Кол-во бутылок'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_weight_bru',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Масса брутто поддона, кг.', max_digits=5, null=True, verbose_name='Масса брутто'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_weight_net',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Масса нетто поддона, кг.', max_digits=5, null=True, verbose_name='Масса нетто'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ширина поддона, м.', max_digits=2, null=True, verbose_name='Ширина поддона'),
        ),
    ]
