# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0019_auto_20171201_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Название бренда', max_length=100, verbose_name='Бренд'),
        ),
    ]
