# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0020_auto_20171201_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tara',
            options={'verbose_name': 'тара', 'verbose_name_plural': 'тары'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='tara',
            field=models.ForeignKey(help_text='Выберите тару', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Tara', verbose_name='тара'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='taste',
            field=models.CharField(blank=True, help_text='Вкус(Груша, Минеральная, Газированная и т.п.', max_length=100, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='material',
            field=models.CharField(help_text='Материал бутылки (ПЭТ, стекло...)', max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_height',
            field=models.IntegerField(blank=True, help_text='Высота упаковки, мм.', null=True, verbose_name='Высота упаковки, мм.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_length',
            field=models.IntegerField(blank=True, help_text='Длина упаковки, мм.', null=True, verbose_name='Длина упаковки, мм.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_quant',
            field=models.IntegerField(blank=True, help_text='Количество бутылок в упаковке, шт.', null=True, verbose_name='Кол-во бутылок, шт.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Вес брутто упаковки, кг.', max_digits=3, null=True, verbose_name='Вес упаковки, кг.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pack_width',
            field=models.IntegerField(blank=True, help_text='Ширина упаковки, мм.', null=True, verbose_name='Ширина упаковки, мм.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Длина поддона, м.', max_digits=2, null=True, verbose_name='Длина поддона, м.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_quant',
            field=models.IntegerField(blank=True, help_text='Количество бутылок на поддоне, шт.', null=True, verbose_name='Кол-во бутылок, шт.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_weight_bru',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Масса брутто поддона, кг.', max_digits=5, null=True, verbose_name='Масса брутто, кг.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_weight_net',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Масса нетто поддона, кг.', max_digits=5, null=True, verbose_name='Масса нетто, кг.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='pallet_width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ширина поддона, м.', max_digits=2, null=True, verbose_name='Ширина поддона, м.'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='volume',
            field=models.DecimalField(decimal_places=2, help_text='Объем бутылки, л.', max_digits=4, verbose_name='Объем, л.'),
        ),
    ]
