# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0021_auto_20171201_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='tara',
            field=models.ForeignKey(help_text='Выберите тару', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Tara', verbose_name='Тара'),
        ),
        migrations.AlterField(
            model_name='tara',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='siteapp.Brand', verbose_name='Бренд'),
        ),
    ]
